services:
  app:
    build:
      context: .
      args:
        - DEV=true
#      target: app
    ports:
      - "8000:8000"
#    restart: always
    volumes:
      - ./app:/app
    # * This is the command run by default
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"